apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaosmeta-platform
  namespace: chaosmeta-platform
  labels:
    release: chaosmeta-platform
    app: chaosmeta-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaosmeta-platform
  template:
    metadata:
      labels:
        app: chaosmeta-platform
    spec:
      serviceAccountName: chaosmeta-platform
      containers:
        - name: chaosmeta-platform
          imagePullPolicy: Always
          image:  registry.cn-hangzhou.aliyuncs.com/chaosmeta/chaosmeta-platform:v0.0.3
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          volumeMounts:
            - name: chaosmeta-config
              mountPath: /home/admin/conf
        - name: chaosmeta-platform-frontend
          imagePullPolicy: Always
          image: registry.cn-hangzhou.aliyuncs.com/chaosmeta/chaosmeta-platform-frontend:v0.0.1
          ports:
            - containerPort: 8000
      volumes:
        - name: chaosmeta-config
          configMap:
            name: chaosmeta-platform
            items:
              - key: app.conf
                path: app.conf
              - key: app.yaml
                path: app.yaml