apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaosmeta-platform
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaosmeta-platform
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["argoproj.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["chaosmeta.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind:  ClusterRoleBinding
metadata:
  name: chaosmeta-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:  ClusterRole
  name: chaosmeta-platform
subjects:
  - kind: ServiceAccount
    name: chaosmeta-platform
    namespace: default