apiVersion: v1
kind: Service
metadata:
  labels:
    app: chaosmeta-platform-mysql
  name: chaosmeta-platform-mysql
  namespace: chaosmeta
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: chaosmeta-platform-mysql
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chaosmeta-platform
  name: chaosmeta-platform
  namespace: chaosmeta
spec:
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  selector:
    app: chaosmeta-platform
  sessionAffinity: None
  type: LoadBalancer
