/*
 * Copyright 2022-2023 Chaos Meta Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaosmeta-platform
rules:
  - apiGroups: ["apps", "batch", "", "extensions", "networking.k8s.io", "rbac.authorization.k8s.io", "apiextensions.k8s.io"]
    resources: ["nodes", "pods", "services", "deployments", "jobs", "ingresses", "configmaps",
                "pods/exec", "replicasets", "statefulsets", "namespaces", "pods/log", "events", "serviceaccounts",
                "secrets", "clusterroles", "clusterrolebindings", "customresourcedefinitions", "pods/ephemeralcontainers",
                "daemonsets"]
    verbs: ["*"]
  - apiGroups: ["inject.chaosmeta.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["events"]
    verbs:
      - create
      - update
      - patch
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind:  ClusterRoleBinding
metadata:
  name: chaosmeta-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:  ClusterRole
  name: chaosmeta-platform
subjects:
  - kind: ServiceAccount
    name: chaosmeta-platform
    namespace: chaosmeta-platform
  {{- end -}}
