---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-chaosmeta-io-v1alpha1-loadtest
  failurePolicy: Fail
  name: mloadtest.kb.io
  rules:
  - apiGroups:
    - chaosmeta.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - loadtests
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-chaosmeta-io-v1alpha1-loadtest
  failurePolicy: Fail
  name: vloadtest.kb.io
  rules:
  - apiGroups:
    - chaosmeta.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - loadtests
  sideEffects: None
