apiVersion: inject.chaosmeta.io/v1alpha1
kind: Experiment
metadata:
  labels:
    app.kubernetes.io/name: experiment
    app.kubernetes.io/instance: experiment-sample
    app.kubernetes.io/part-of: chaosmeta-inject-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: chaosmeta-inject-operator
  name: node-experiment
spec:
  scope: node
  targetPhase: inject
  rangeMode:
    type: all
    value: 30
  experiment:
    target: cpu
    fault: burn
    duration: 2m
    args:
      - key: percent
        value: '80'
        valueType: int
      - key: count
        value: '2'
        valueType: int
  selector:
    - name:
        - test1
        - test2
    - label:
        app: app1
        os: linux
    - ip:
        - 1.1.1.1
        - 1.1.1.2