apiVersion: chaosmeta.io/v1alpha1
kind: Experiment
metadata:
  name: kubernetes-deployment-label
  namespace: chaosmeta-inject
spec:
  scope: kubernetes
  targetPhase: inject
  experiment:
    target: deployment
    fault: label
    duration: 2m
    args:
      - key: add
        value: "k1=v2"
        valueType: string
  selector:
    - namespace: default