apiVersion: inject.chaosmeta.io/v1alpha1
kind: Experiment
metadata:
#  labels:
#    app.kubernetes.io/name: experiment
#    app.kubernetes.io/instance: experiment-sample
#    app.kubernetes.io/part-of: chaosmeta-inject-operator
#    app.kubernetes.io/managed-by: kustomize
#    app.kubernetes.io/created-by: chaosmeta-inject-operator
  name: kubernetes-pod-containerkill
spec:
  scope: kubernetes
  targetPhase: inject
  experiment:
    target: pod
    fault: containerkill
    duration: 2m
    args:
      - key: containername
        value: "firstcontainer"
        valueType: string
  selector:
    - namespace: default
      name:
        - frontend