# permissions for end users to view commonmeasures.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: commonmeasure-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: chaosmeta-measure-operator
    app.kubernetes.io/part-of: chaosmeta-measure-operator
    app.kubernetes.io/managed-by: kustomize
  name: commonmeasure-viewer-role
rules:
- apiGroups:
  - chaosmeta.io
  resources:
  - commonmeasures
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - chaosmeta.io
  resources:
  - commonmeasures/status
  verbs:
  - get
