# permissions for end users to edit commonmeasures.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: commonmeasure-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: chaosmeta-measure-operator
    app.kubernetes.io/part-of: chaosmeta-measure-operator
    app.kubernetes.io/managed-by: kustomize
  name: commonmeasure-editor-role
rules:
- apiGroups:
  - chaosmeta.io
  resources:
  - commonmeasures
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chaosmeta.io
  resources:
  - commonmeasures/status
  verbs:
  - get
