apiVersion: chaosmeta.io/v1alpha1
kind: CommonMeasure
metadata:
  name: measure-udp-true
  namespace: chaosmeta-measure
spec:
  measureType: udp
  duration: 10m
  interval: 5s
  successCount: 3
  failedCount: 0
  stopped: false
  judgement:
    judgeType: connectivity
    judgeValue: 'true'
  args:
    - key: ip
      value: '192.168.2.189'
    - key: port
      value: '8082'
    - key: timeout
      value: '5'
